[workspace]
resolver = "3"
members = [
    "utils",
    "macros",
    "drivers",
    "scheduler", 
    "hypervisor",
    "boot",
    "logger", 
    "pmm", 
    "slab", 
    "kernel",
]

[profile.dev]
debug = true
panic = "abort"

[profile.release]
panic = "abort"
