[workspace]
resolver = "3"
members = [
    "utils",
    "macros",
    "drivers",
    "scheduler", 
    "hypervisor",
    "boot",
    "kernel", 
    "logger",
]

[profile.dev]
debug = true
panic = "abort"

[profile.release]
panic = "abort"

