[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
limine = { version = "0.3.1", optional = true }

alloc = { version = "1.0.0", package = "rustc-std-workspace-alloc"}

modular-bitfield = { version = "0.11.2"}
utils = { path = "../utils" }
macros = { path = "../macros" }

[features]
default = ["limine", "amd", "framebuffer", "serial", "paging_4", "pmm_bump", "mp", "hpet"]

# x86_64 CPU vendors. Pick the one you intend to use.
intel = []
amd = []

# Booting method
limine = ["dep:limine"]

# Logging methods
serial = []
framebuffer = []

# Paging modes. Only one can be enabled (TODO: Remove this limitation)
paging_4 = []
paging_5 = [] # UNTESTED

# PMM page allocator algorithm. Only one can be enabled
pmm_bump = []
pmm_buddy = []

# Disable on the weird case you wouldn't want to use multiple cores on the system
mp = []

# Choose which general timer to use.
# If the HPET feature is enabled and the HPET is found during boot, the system will use HPET.
# Otherwise if the PIT feature is enabled and the PIT is found the system will use PIT.
# Otherwise, the system will error out. So you must enable one of them (or both).
hpet = []
pit = []


[profile.dev]
debug = true
panic = "abort"

[profile.release]
debug = true
panic = "abort"
