[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
limine = { version = "0.3.1", optional = true }
alloc = { version = "1.0.0", package = "rustc-std-workspace-alloc"}
utils = { path = "../utils" }

[features]
# default = []
default = ["limine", "amd", "serial", "paging_4", "pmm_buddy"]

# x86_64 CPU vendors
intel = []
amd = []

# booting method
limine = ["dep:limine"]

# logging methods
serial = []
framebuffer = []

# paging modes
paging_4 = []
paging_5 = [] # UNTESTED

# PMM page allocator algorithm
pmm_bump = []
pmm_buddy = [] # NOT SUPPORTED YET!

