[package]
name = "logger"
version = "0.1.0"
edition = "2024"

[dependencies]
limine = { version = "0.5.0", optional = true }

[features]
default = ["limine", "serial", "framebuffer"]

# Booting method
limine = ["dep:limine"]

# Logging methods
serial = []
framebuffer = []

